'use client';

import Image from 'next/image';
import { ProjectStory, StoryStation, StoryBridge } from './ProjectStory';
import { AnimatedDisclosure, HeroTitle, HeroVisual, MethodStep, ReadingProgress } from './PremiumMotion';
import { useEffect, useId, useRef, useState, type ReactNode } from 'react';
import { AnimatePresence, MotionConfig, motion, useInView, useReducedMotion } from 'framer-motion';
import { ArrowRight, ArrowUpRight, ArrowDown, Check, ChevronDown, Menu, X, Network, Globe2, Layers3, LayoutDashboard, ShieldCheck, Wifi, Monitor, Phone, Code2, Database, FileText, Plus, Camera } from 'lucide-react';

const services = [
  { title:'Réseaux & infrastructures', short:'Une base fiable pour votre activité.', icon:Network, description:'Un réseau pensé pour vos espaces, vos équipements et vos usages. Nous concevons et organisons votre infrastructure pour que votre équipe puisse travailler sereinement.', details:['Réseaux professionnels & Wi-Fi','Installation et configuration des équipements','Séparation des accès & sécurisation'], topic:'Réseau & Wi-Fi' },
  { title:'Sites web & e-commerce', short:'Une présence à la hauteur de votre marque.', icon:Globe2, description:'Un site qui exprime votre identité, présente votre savoir-faire et facilite la prise de contact. De la vitrine à la boutique en ligne, chaque interface est pensée pour vos visiteurs.', details:['Sites vitrines & boutiques en ligne','Design responsive & parcours utilisateur','Intégration, mise en ligne & évolution'], topic:'Site web & e-commerce' },
  { title:'Logiciels métier & ERP', short:'Vos processus. Votre outil.', icon:Layers3, description:'Quand les outils standards ne suivent plus votre façon de travailler, nous concevons une application adaptée. Un logiciel qui rassemble les données et simplifie le quotidien.', details:['Applications web, bureau & mobile','Gestion, facturation & suivi d’activité','Automatisation des tâches métier'], topic:'Logiciel & ERP' },
  { title:'CRM & back-offices', short:'Une vision claire, des équipes alignées.', icon:LayoutDashboard, description:'Centralisez votre relation client, pilotez votre activité et donnez à vos équipes une interface claire. Des espaces de gestion construits autour de vos besoins réels.', details:['Suivi des clients & des opportunités','Tableaux de bord & interfaces d’administration','Organisation des données & des accès'], topic:'CRM & back-office' },
];
const faq = [
 ['Comment démarre un projet avec SkanCyber ?', 'Nous commençons par un échange sur votre activité, vos outils actuels et vos objectifs. Nous définissons ensuite un périmètre et une proposition adaptés à votre besoin.'],
 ['Pouvez-vous faire évoluer un système existant ?', 'Oui. Un projet peut commencer par une installation réseau, un site ou une application déjà en place. L’objectif est de comprendre l’existant avant de proposer une évolution cohérente.'],
 ['Que peut-on concevoir sur mesure ?', 'Un site web, une boutique en ligne, un logiciel métier, un ERP, un CRM ou un back-office. Le périmètre, les intégrations et les fonctionnalités sont définis avec vous selon vos processus.'],
 ['Travaillez-vous à distance ?', 'La conception et le développement peuvent être réalisés à distance. Pour une intervention réseau sur place, nous précisons ensemble le lieu, les besoins et les modalités.'],
];
function Reveal({children,className='',delay=0,id}:{children:ReactNode;className?:string;delay?:number;id?:string}){const reduced=useReducedMotion();return <motion.div id={id} className={className} initial={reduced?false:{opacity:0,y:22}} whileInView={{opacity:1,y:0}} viewport={{once:true,amount:.12}} transition={{duration:reduced?0:.6,delay:reduced?0:delay,ease:[.22,1,.36,1]}}>{children}</motion.div>}
function Logo(){return <a className="p-logo" href="#accueil" aria-label="SkanCyber, accueil"><svg viewBox="0 0 32 32" fill="none" aria-hidden="true"><path d="M7 8h18v6H13v4h12v6H7v-6h12v-4H7Z" fill="currentColor"/></svg><span>skancyber<span>.</span></span></a>}
function Label({children,light=false}:{children:ReactNode;light?:boolean}){return <span className={`p-label ${light?'light':''}`}><i/>{children}</span>}
export default function PremiumSite(){
 const [chapter,setChapter]=useState('accueil');
 const [menu,setMenu]=useState(false),[selected,setSelected]=useState(0),[topic,setTopic]=useState('Votre projet'),[openFaq,setOpenFaq]=useState<number|null>(0);
 const reduced=!!useReducedMotion();const menuRef=useRef<HTMLButtonElement>(null);
 const explore=(index:number)=>{setSelected(index);document.getElementById('expertises')?.scrollIntoView({behavior:reduced?'auto':'smooth'})};
 const ask=(name:string)=>{setTopic(name);document.getElementById('contact')?.scrollIntoView({behavior:reduced?'auto':'smooth'})};
 useEffect(()=>{if(!menu)return;document.querySelector<HTMLAnchorElement>('.p-mobile-nav a')?.focus();const key=(e:KeyboardEvent)=>{if(e.key==='Escape'){setMenu(false);menuRef.current?.focus()}};document.addEventListener('keydown',key);return()=>document.removeEventListener('keydown',key)},[menu]);
 useEffect(()=>{
  const sections=[...document.querySelectorAll<HTMLElement>('[data-chapter]')];
  const observer=new IntersectionObserver(entries=>{for(const entry of entries){if(entry.isIntersecting)setChapter((entry.target as HTMLElement).dataset.chapter!)}},{rootMargin:'-20% 0px -65% 0px',threshold:0});
  sections.forEach(section=>observer.observe(section));
  return()=>observer.disconnect();
 },[]);
 return <MotionConfig reducedMotion="user"><div className="premium-site" id="accueil">
 <a className="p-skip" href="#contenu">Aller au contenu</a>
 <ReadingProgress/><ProjectStory/><header className="p-header"><Logo/><nav className="p-desktop-nav" aria-label="Navigation principale"><a href="#expertises" aria-current={chapter==='expertises'?'location':undefined}>Nos expertises</a><a href="#realisations" aria-current={chapter==='realisations'?'location':undefined}>Réalisations</a><a href="#approche" aria-current={chapter==='approche'?'location':undefined}>Notre approche</a></nav><a className="p-header-cta" href="#contact">Parlons de votre projet <ArrowUpRight size={16}/></a><button ref={menuRef} className="p-menu" aria-label={menu?'Fermer le menu':'Ouvrir le menu'} aria-expanded={menu} aria-controls="navigation-mobile" onClick={()=>setMenu(m=>!m)}>{menu?<X size={22}/>:<Menu size={22}/>}</button><AnimatePresence>{menu&&<motion.nav className="p-mobile-nav" id="navigation-mobile" aria-label="Navigation mobile" initial={{opacity:reduced?1:0,y:reduced?0:-10}} animate={{opacity:1,y:0}} exit={{opacity:0}}>{[['Nos expertises','expertises'],['Réalisations','realisations'],['Notre approche','approche'],['Votre projet','contact']].map(([label,id],i)=><a href={`#${id}`} key={id} onClick={()=>setMenu(false)}><span>0{i+1}</span>{label}<ArrowUpRight size={18}/></a>)}</motion.nav>}</AnimatePresence></header>
 <main id="contenu">
  <section className="p-hero" data-chapter="accueil"><div className="p-hero-layout"><div className="p-hero-copy"><Label light>VOTRE PARTENAIRE TECHNIQUE</Label><HeroTitle/><p>Réseaux professionnels, sites web et logiciels sur mesure.<br className="desktop-break"/> SkanCyber conçoit les fondations et les outils qui font avancer votre entreprise.</p><div className="p-hero-actions"><a className="p-button mint" href="#contact">Construisons votre projet <ArrowUpRight size={18}/></a><a className="p-discover" href="#expertises">Découvrir nos expertises <ArrowDown size={15}/></a></div><div className="p-hero-proof"><span className="p-proof-symbol"><Check size={12}/></span><span>Un interlocuteur. Une vision d’ensemble.<br/><strong>De l’infrastructure à l’application.</strong></span></div></div><HeroVisual><div className="p-image-frame"><Image src="/images/infrastructure.jpg" alt="Illustration d’une infrastructure réseau professionnelle organisée" fill priority sizes="(max-width: 700px) 100vw, 48vw" unoptimized/><div className="p-photo-shade"/><div className="p-image-caption"><span className="p-live-dot"/><span>Des fondations solides.<br/><strong>Pour des projets durables.</strong></span><Network size={23}/></div><div className="p-corner-code">SK / INFRASTRUCTURE</div></div><div className="p-system-card"><div className="p-system-title"><span className="p-system-icon"><Layers3 size={18}/></span><span>L’ensemble fait la différence.<small>NOTRE VISION DU NUMÉRIQUE</small></span></div><div className="p-system-row"><button onClick={()=>explore(0)} aria-label="Explorer réseaux"><Network size={13}/>Réseaux</button><i/><button onClick={()=>explore(1)} aria-label="Explorer interfaces"><Code2 size={13}/>Interfaces</button><i/><button onClick={()=>explore(3)} aria-label="Explorer données"><Database size={13}/>Données</button></div></div></HeroVisual></div><div className="p-hero-base"><StoryStation index={0}/><div><a href="#expertises" onClick={()=>setSelected(0)}><Network size={17}/>Réseaux & Wi-Fi<ArrowUpRight size={12}/></a><a href="#expertises" onClick={()=>setSelected(1)}><Globe2 size={17}/>Web & e-commerce<ArrowUpRight size={12}/></a><a href="#expertises" onClick={()=>setSelected(2)}><Layers3 size={17}/>Logiciels & gestion<ArrowUpRight size={12}/></a></div></div></section><StoryBridge index={0}/>
  <section className="p-intro p-section" id="expertises" data-chapter="expertises"><Reveal className="p-intro-top"><Label>LE BON PARTENAIRE, DU DÉBUT À LA SUITE</Label><span className="p-section-no">01 / EXPERTISES</span></Reveal><div className="p-section-heading"><Reveal><h2>Du réseau à l’application.<br/><span>Nous pensons l’ensemble.</span></h2></Reveal><Reveal delay={.1}><p>Votre informatique doit soutenir votre activité. Nous associons infrastructure, design et développement pour construire des solutions cohérentes, utiles et adaptées à votre métier.</p></Reveal></div><StoryStation index={1}/><div className="p-expertise-layout"><div className="p-service-list">{services.map((s,i)=>{const Icon=s.icon;const active=selected===i;return <article className={`p-service ${active?'active':''}`} key={s.title}><button className="p-service-trigger" id={`service-${i}`} aria-expanded={active} aria-controls={`service-details-${i}`} onClick={()=>setSelected(i)}><span className="p-service-number">0{i+1}</span><span className="p-service-name"><Icon size={21}/><strong>{s.title}</strong></span><Plus size={18} className="p-service-plus"/></button><AnimatedDisclosure id={`service-details-${i}`} open={active}><div className="p-service-details"><p>{s.description}</p><ul>{s.details.map(d=><li key={d}><Check size={13}/>{d}</li>)}</ul><button className="p-text-link" onClick={()=>ask(s.topic)}>Parlons de votre besoin <ArrowUpRight size={16}/></button>{(i===0||i===2)&&<a className="p-service-proof" href={i===0?'#projet-reseau':'#projet-logiciel'}>Voir une réalisation de cette expertise <ArrowDown size={12}/></a>}</div></AnimatedDisclosure></article>})}</div><div className="p-expertise-preview"><div className="p-preview-heading"><span>UNE EXPERTISE, DES POSSIBILITÉS.</span><span>0{selected+1} / 04</span></div><AnimatePresence mode="wait" initial={false}><motion.div key={selected} initial={{opacity:reduced?1:0,y:reduced?0:12}} animate={{opacity:1,y:0}} exit={{opacity:reduced?1:0,y:reduced?0:-8}} transition={{duration:reduced?0:.2}}><ServicePreview index={selected}/></motion.div></AnimatePresence><div className="p-preview-footer"><span className="p-live-dot"/><span>{services[selected].short}</span><span>APERÇU CONCEPTUEL</span></div></div></div></section><StoryBridge index={1}/>
  <section className="p-projects p-section" id="realisations" data-chapter="realisations"><div className="p-intro-top"><Label>DES PROJETS ANCRÉS DANS LE RÉEL</Label><span className="p-section-no">02 / RÉALISATIONS</span></div><div className="p-section-heading"><Reveal><h2>Des besoins concrets.<br/><span>Des réponses adaptées.</span></h2></Reveal><Reveal delay={.1}><p>Un logiciel de gestion ou un réseau de restaurant : le point de départ reste le même. Comprendre l’usage et construire la bonne solution.</p></Reveal></div><StoryStation index={2}/><div className="p-project-grid"><Reveal id="projet-logiciel" className="p-project-card"><div className="p-project-picture fact"><div className="p-project-mini-label">SKANFACT / LOGICIEL DE GESTION</div><InvoicePreview/></div><div className="p-project-description"><span className="p-project-category">LOGICIEL MÉTIER · TUNISIE</span><a href="https://skanfact.tn" target="_blank" rel="noreferrer"><h3>SkanFact. La gestion, réunie.</h3><span className="p-project-arrow"><ArrowUpRight size={19}/></span></a><p>Devis, factures, stock, trésorerie et comptabilité. Une solution qui fonctionne aussi hors ligne, pensée pour les PME tunisiennes.</p><div className="p-project-tags"><span>Gestion & facturation</span><span>Fonctionnement hors ligne</span></div><button className="p-project-explore" onClick={()=>explore(2)}>Explorer l’expertise logiciel <ArrowUpRight size={14}/></button></div></Reveal><Reveal id="projet-reseau" className="p-project-card" delay={.1}><div className="p-project-picture network"><div className="p-project-mini-label">STRASBOURG / INFRASTRUCTURE RÉSEAU</div><NetworkPreview compact/></div><div className="p-project-description"><span className="p-project-category">RÉSEAU PROFESSIONNEL · FRANCE</span><button onClick={()=>ask('Réseau & Wi-Fi')}><h3>Un restaurant. Un réseau organisé.</h3><span className="p-project-arrow"><ArrowUpRight size={19}/></span></button><p>Une installation UniFi avec trois bornes Wi-Fi et quatre réseaux séparés pour les équipes, la caisse, les invités et les caméras.</p><div className="p-project-tags"><span>Wi-Fi professionnel</span><span>Séparation des accès</span></div><button className="p-project-explore" onClick={()=>explore(0)}>Explorer l’expertise réseau <ArrowUpRight size={14}/></button></div></Reveal></div></section><StoryBridge index={2}/>
  <section className="p-approach p-section" id="approche" data-chapter="approche"><div className="p-intro-top"><Label light>UNE MÉTHODE CLAIRE. UN LIEN DIRECT.</Label><span className="p-section-no">03 / APPROCHE</span></div><div className="p-approach-heading"><Reveal><h2>La technique est notre métier.<br/><span>Votre activité est le point de départ.</span></h2></Reveal><p>Des échanges directs, des choix expliqués et un périmètre défini ensemble. Pour que votre projet avance avec une direction claire.</p></div><StoryStation index={3}/><div className="p-steps">{[['Comprendre','Votre métier, vos usages, vos contraintes. Nous posons les bonnes questions avant de proposer une solution.'],['Concevoir','Une architecture et une interface adaptées. Le projet prend forme autour de votre façon de travailler.'],['Déployer','Développer, configurer, vérifier. Puis mettre votre solution en place avec le soin qu’elle mérite.'],['Accompagner','Prendre en main, ajuster, faire évoluer. Les modalités de suivi sont définies avec vous.']].map(([t,p],i)=><Reveal key={t} delay={i*.06}><MethodStep index={i} title={t}>{p}</MethodStep></Reveal>)}</div><Reveal className="p-founder"><div className="p-founder-avatar">SB</div><div><h3>Skander Ben Amor</h3><span>FONDATEUR & INTERLOCUTEUR TECHNIQUE</span></div><p>Développeur d’applications métier, formé à la cybersécurité. Une vue d’ensemble pour relier vos outils, votre réseau et vos usages.</p><a href="#contact">Échangeons directement <ArrowUpRight size={16}/></a></Reveal></section><StoryBridge index={3}/>
  <section className="p-faq p-section"><Reveal><Label>AVANT DE COMMENCER</Label><h2>Quelques questions.<br/><span>Des réponses simples.</span></h2><p>Chaque projet a ses particularités.<br/>Le premier échange permet de préciser les vôtres.</p></Reveal><div className="p-faq-list">{faq.map(([q,a],i)=><article className={openFaq===i?'open':''} key={q}><button aria-expanded={openFaq===i} aria-controls={`faq-answer-${i}`} onClick={()=>setOpenFaq(v=>v===i?null:i)}><span>{q}</span><Plus size={19}/></button><AnimatedDisclosure id={`faq-answer-${i}`} open={openFaq===i}><p>{a}</p></AnimatedDisclosure></article>)}</div></section>
  <section className="p-contact p-section" id="contact" data-chapter="contact"><div className="p-contact-copy"><Label>FAISONS AVANCER VOTRE PROJET</Label><h2>Une ambition.<br/><span>Parlons-en.</span></h2><p>Un réseau à repenser, un site à créer, un logiciel à concevoir.<br/>Commençons par votre besoin.</p><div className="p-topic"><label htmlFor="p-project-topic">VOTRE SUJET</label><select id="p-project-topic" value={topic} onChange={e=>setTopic(e.target.value)}>{['Votre projet',...services.map(s=>s.topic)].map(t=><option key={t}>{t}</option>)}</select></div></div><div className="p-contact-card"><StoryStation index={4}/><span className="p-contact-title">UN CONTACT DIRECT AVEC SKANCYBER</span><div className="p-contact-context" aria-live="polite"><AnimatePresence mode="wait" initial={false}><motion.span key={topic} initial={{opacity:0,y:8}} animate={{opacity:1,y:0}} exit={{opacity:0,y:-8}} transition={{duration:reduced?0:.18}}><span className="p-live-dot"/>{topic==='Votre projet'?'Tout commence par un échange.':topic}</motion.span></AnimatePresence></div><a href="tel:+33672313188"><span className="p-country">FRANCE</span><strong>+33 6 72 31 31 88</strong><span className="p-call-icon"><Phone size={18}/></span></a><a href="tel:+21650800600"><span className="p-country">TUNISIE</span><strong>+216 50 800 600</strong><span className="p-call-icon"><Phone size={18}/></span></a><div className="p-contact-bottom"><span><Check size={12}/>Une proposition adaptée à votre projet.</span><span>PRESTATIONS SUR DEVIS</span></div></div></section>
 </main><footer className="p-footer p-section"><div className="p-footer-top"><div><Logo/><p>Réseaux, web et logiciels sur mesure.<br/>Un partenaire pour penser l’ensemble.</p></div><nav aria-label="Navigation de pied de page"><a href="#expertises">Expertises</a><a href="#realisations">Réalisations</a><a href="#approche">Approche</a><a href="#contact">Contact</a></nav><a className="p-back-top" href="#accueil">Retour en haut <ArrowUpRight size={15}/></a></div><details className="p-legal"><summary>Informations légales</summary><div><p>SKANCYBER SECURITY SUARL — gestion d’installations informatiques. 08 Rue de l’Université, Manar 1, El Menzah, Tunis 2092, Tunisie. Matricule fiscal : 1998268 D/A/M/000. Gérant : Skander Ben Amor.</p><p>Hébergement : Vercel Inc. Polices locales. Aucun cookie de suivi ni mesure d’audience. Les interfaces d’aperçu utilisent des données fictives. Le visuel d’infrastructure est une illustration créée pour le site. Les modalités, zones d’intervention et périmètres des prestations sont définis avec vous.</p></div></details><div className="p-footer-bottom"><span>© 2026 SkanCyber Security SUARL</span><span>Concevoir. Connecter. Faire avancer.</span><span>France · Tunisie</span></div></footer>
 </div></MotionConfig>;
}
function ServicePreview({index}:{index:number}){return <div className={`p-preview-body preview-${index}`}>{index===0?<NetworkPreview/>:index===1?<WebsitePreview/>:index===2?<InvoicePreview/>:<CrmPreview/>}</div>}
function NetworkPreview({compact=false}:{compact?:boolean}){
 const ref=useRef<HTMLDivElement>(null);const inView=useInView(ref,{margin:'0px'});const [zone,setZone]=useState(0);const reduced=useReducedMotion();
 const zones=[{icon:Wifi,name:'Équipe',detail:'Les outils de travail restent dans un espace réservé aux équipes.'},{icon:Monitor,name:'Caisse',detail:'Les équipements de caisse disposent de leur propre réseau.'},{icon:Globe2,name:'Invités',detail:'L’accès des visiteurs est séparé des usages professionnels.'},{icon:Camera,name:'Caméras',detail:'Les équipements de surveillance sont regroupés sur un accès dédié.'}];
 return <div ref={ref} data-active={inView} className={`p-network ${compact?'compact':''}`}><div className="p-net-heading"><span>INFRASTRUCTURE PROFESSIONNELLE</span><ShieldCheck size={15}/></div><div className="p-router"><Network size={25}/><strong>Réseau central</strong><span>UNIFI / UDR 7</span></div><div className="p-net-connector"><i/><i/><i/><i/><b className="p-net-packet" aria-hidden="true"/></div><div className="p-net-zones">{zones.map((z,i)=>{const Icon=z.icon;return <div key={z.name} className={zone===i?'selected':''}><button aria-label={`Explorer le réseau ${z.name.toLowerCase()}`} aria-pressed={zone===i} onClick={()=>setZone(i)}><Icon size={21}/></button><strong>{z.name}</strong><small>ACCÈS SÉPARÉ</small></div>})}</div>{compact?<div className="p-net-security"><ShieldCheck size={13}/><span>Des accès organisés. Des usages protégés.</span></div>:<div className="p-zone-details" aria-live="polite"><AnimatePresence mode="wait" initial={false}><motion.div key={zone} initial={{opacity:0,y:6}} animate={{opacity:1,y:0}} exit={{opacity:0,y:-6}} transition={{duration:reduced?0:.15}}><span><ShieldCheck size={13}/>{zones[zone].name} · Accès séparé</span><p>{zones[zone].detail}</p></motion.div></AnimatePresence><small>Sélectionnez un usage pour explorer le schéma.</small></div>}</div>;
}
function InvoicePreview(){const chartId=useId();const reduced=useReducedMotion();return <div className="p-invoice"><aside><span className="p-app-logo">sf.</span><LayoutDashboard size={15}/><FileText size={15}/><Layers3 size={15}/><div>SB</div></aside><div className="p-invoice-main"><div className="p-app-top"><span>Vue d’ensemble</span><span><i/>Hors ligne</span></div><div className="p-app-greeting"><h4>Votre activité, en clair.</h4><span>Données de démonstration</span></div><div className="p-app-stat"><span>FACTURATION DU MOIS</span><strong>12 480<small>TND</small></strong><svg viewBox="0 0 420 75" aria-label="Courbe d’activité fictive" role="img"><defs><linearGradient id={chartId} x1="0" y1="0" x2="0" y2="1"><stop stopColor="#258268" stopOpacity=".2"/><stop offset="1" stopColor="#258268" stopOpacity="0"/></linearGradient></defs><path d="M0 60C35 62 25 41 55 45S90 68 125 40S150 42 175 29S220 56 245 34S270 51 300 23S355 48 380 18S409 16 420 4V75H0Z" fill={`url(#${chartId})`}/><motion.path initial={reduced?false:{pathLength:0}} whileInView={{pathLength:1}} viewport={{once:true}} transition={{duration:reduced?0:1.4,ease:[.22,1,.36,1]}} d="M0 60C35 62 25 41 55 45S90 68 125 40S150 42 175 29S220 56 245 34S270 51 300 23S355 48 380 18S409 16 420 4" stroke="#258268" strokeWidth="2" fill="none"/></svg></div><div className="p-app-table-head"><span>Dernières factures</span><span>Tout voir →</span></div>{[['FA-2026-0142','2 400 TND','Payée'],['FA-2026-0141','1 850 TND','Envoyée']].map(([n,a,s])=><div className="p-app-table-row" key={n}><FileText size={12}/><span>{n}</span><b>{a}</b><small className={s==='Payée'?'paid':''}>{s}</small></div>)}</div></div>}
function WebsitePreview(){const [mobile,setMobile]=useState(false);return <div className={`p-web-demo ${mobile?'mobile-focus':''}`}><div className="p-demo-controls"><button aria-pressed={!mobile} onClick={()=>setMobile(false)}><Monitor size={11}/>Ordinateur</button><button aria-pressed={mobile} onClick={()=>setMobile(true)}>Mobile <ArrowUpRight size={11}/></button></div><div className="p-web-preview"><div className="p-browser"><span><i/><i/><i/></span><span>Votre site, votre identité.</span><ArrowUpRight size={11}/></div><div className="p-web-page"><header><b>Maison / Atelier</b><span>Collection&nbsp;&nbsp; Notre savoir-faire&nbsp;&nbsp; Contact</span></header><div className="p-web-hero"><div><span>LE SAVOIR-FAIRE, EN LIGNE</span><h4>L’essentiel.<br/>Bien présenté.</h4><p>Un univers à votre image.<br/>Une expérience pensée pour vos clients.</p><span className="p-web-button">Découvrir la collection <ArrowUpRight size={10}/></span></div><div className="p-web-product"><div className="p-lamp-shade"/><div className="p-lamp-neck"/><div className="p-lamp-base"/><span>Objet de démonstration</span></div></div><footer><span>Une identité claire</span><span>Un parcours fluide</span><span>Tous les écrans</span></footer></div><div className="p-web-mobile"><span/><strong>Maison /<br/>Atelier</strong><div className="p-mobile-lamp"/><p>L’essentiel.<br/>Bien présenté.</p></div></div></div>}
function CrmPreview(){return <div className="p-crm"><div className="p-crm-title"><span><LayoutDashboard size={17}/>Votre espace de pilotage</span><span>APERÇU CRM</span></div><h4>Les bonnes informations.<br/>Au bon endroit.</h4><div className="p-crm-stats">{[['12','Contacts'],['08','Opportunités'],['03','Projets']].map(([n,l])=><div key={l}><strong>{n}</strong><span>{l}</span></div>)}</div><div className="p-crm-board">{[['À qualifier','Projet web','Nouveau contact'],['En cours','Application métier','Échange technique'],['Proposition','Réseau & Wi-Fi','Périmètre à valider']].map(([s,t,c],i)=><div key={s}><span><i/>{s}</span><div><small>SC / 00{i+1}</small><strong>{t}</strong><p>{c}</p><span><span className="p-crm-avatar">SB</span><ArrowUpRight size={11}/></span></div></div>)}</div><span className="p-crm-note">Interface conceptuelle · Données fictives</span></div>}
