'use client';
import { useState } from 'react';
import { AnimatePresence, motion } from 'framer-motion';
import { ArrowUpRight, Check, Plus, Minus, ShoppingBag, FileText, Columns3, Circle, ArrowRight } from 'lucide-react';

export const products = [
  { name: 'SkanFact', tag: 'La gestion, en clair.', category: 'FACTURATION & GESTION', color: '#2448ee', title: 'Moins de saisie.\nPlus de maîtrise.', description: 'Devis, factures, stock, trésorerie et paie. Votre gestion au même endroit, même hors ligne. Et une comptabilité déjà écrite pour votre expert-comptable.', audience: 'Pour les PME tunisiennes', features: ['Devis & facturation', 'Stock & trésorerie', 'Comptabilité sans ressaisie'] },
  { name: 'SkanEcom', tag: 'Le commerce, sans limites.', category: 'SITES E-COMMERCE', color: '#fc5b35', title: 'Du terrain\nà la boutique.', description: 'Votre commerce mérite une présence en ligne à son image. SkanEcom est la solution du groupe dédiée à la création de sites e-commerce.', audience: 'Pour les commerces', features: ['Identité de votre boutique', 'Présence en ligne', 'Projet adapté à votre activité'] },
  { name: 'SkanRestau', tag: 'Le service, bien orchestré.', category: 'LOGICIEL DE RESTAURATION', color: '#596743', title: 'Le bon outil.\nEn plein service.', description: 'Un métier avec ses propres rythmes, ses propres contraintes. SkanRestau est le logiciel du groupe dédié à la restauration.', audience: 'Pour les restaurateurs', features: ['Pensé pour la restauration', 'Une approche de terrain', 'Un interlocuteur technique'] },
];
export default function ProductLab({ selected, onSelect, ask, reduced }: { selected: number; onSelect: (i: number) => void; ask: (name: string) => void; reduced: boolean }) {
  const product = products[selected];
  return <section className="products-section" id="solutions" style={{ '--product-color': product.color } as React.CSSProperties}>
    <div className="section-index"><span>02 — DES OUTILS QUI SUIVENT</span><span>UNE FAMILLE. TROIS MÉTIERS.</span></div>
    <div className="products-heading"><h2>À chaque métier,<br/><span>son allié.</span></h2><p>Un même regard sur l’informatique.<br/>Des outils qui parlent votre langue.</p></div>
    <div className="product-selector" role="tablist" aria-label="Les solutions du groupe">{products.map((p,i)=><button role="tab" id={`solution-tab-${i}`} key={p.name} aria-controls="solution-panel" aria-selected={selected===i} tabIndex={selected===i?0:-1} onClick={()=>onSelect(i)} onKeyDown={e=>{let next=i;if(e.key==='ArrowRight')next=(i+1)%3;else if(e.key==='ArrowLeft')next=(i+2)%3;else if(e.key==='Home')next=0;else if(e.key==='End')next=2;else return;e.preventDefault();onSelect(next);document.getElementById(`solution-tab-${next}`)?.focus();}}><span className="product-number">0{i+1}</span><strong>{p.name}</strong><ArrowUpRight size={24}/>{selected===i&&<motion.span className="selector-indicator" layoutId="product-indicator" transition={{duration:reduced?0:.45,ease:[.22,1,.36,1]}}/>}</button>)}</div>
    <div className="product-panel" role="tabpanel" id="solution-panel" aria-labelledby={`solution-tab-${selected}`}>
      <AnimatePresence mode="wait" initial={false}><motion.div className="product-description" key={selected} initial={{opacity:reduced?1:0,y:reduced?0:15}} animate={{opacity:1,y:0}} exit={{opacity:reduced?1:0,y:reduced?0:-12}} transition={{duration:reduced?0:.25}}><span className="eyebrow"><i/>{product.audience}</span><h3>{product.title}</h3><p>{product.description}</p><ul>{product.features.map(f=><li key={f}><Check size={15}/>{f}</li>)}</ul>{selected===0?<a className="text-action" href="https://skanfact.tn" target="_blank" rel="noreferrer">Découvrir SkanFact <ArrowUpRight/></a>:<button className="text-action" onClick={()=>ask(product.name)}>Parlons de {product.name}<ArrowUpRight/></button>}<span className="product-status">{selected===0?'LE LOGICIEL RÉEL → SKANFACT.TN':'APERÇU DE CONCEPT · PÉRIMÈTRE SUR ÉCHANGE'}</span></motion.div></AnimatePresence>
      <div className="lab-frame"><div className="lab-toolbar"><span className="window-lights"><i/><i/><i/></span><span>{product.name.toLowerCase()} / aperçu interactif</span><span>DÉMO</span></div><AnimatePresence mode="wait" initial={false}><motion.div key={selected} initial={{opacity:reduced?1:0,scale:reduced?1:.97}} animate={{opacity:1,scale:1}} exit={{opacity:reduced?1:0}} transition={{duration:reduced?0:.25}}>{selected===0?<InvoiceDemo/>:selected===1?<CommerceDemo/>:<RestaurantDemo/>}</motion.div></AnimatePresence><div className="lab-caption"><span><Circle size={7} fill="currentColor"/> Essayez. C’est fait pour ça.</span><span>{selected===0?'Données fictives':'Concept d’interface'}</span></div></div>
    </div>
    <div className="bespoke"><span className="eyebrow">ET SI VOTRE MÉTIER SORT DU CADRE ?</span><p>On construit aussi<br/>l’outil qui vous manque.</p><button onClick={()=>ask('Logiciel sur mesure')} aria-label="Parler d’un logiciel sur mesure"><ArrowUpRight size={30}/></button><span className="bespoke-tag">WEB / BUREAU / MOBILE</span></div>
  </section>;
}
function InvoiceDemo(){const [view,setView]=useState(0),[paid,setPaid]=useState(false);return <div className="invoice-demo"><aside><span className="mini-logo">sf.</span><FileText size={20}/><Columns3 size={20}/><span className="mini-avatar">SB</span></aside><div className="invoice-main"><header><span>VOTRE ESPACE DE GESTION</span><span className="local-badge"><i/> HORS LIGNE</span></header><h4>{view===0?'Une bonne journée.':'Tout est en vue.'}</h4><div className="lab-tabs">{['Factures','Trésorerie'].map((t,i)=><button key={t} aria-pressed={view===i} onClick={()=>setView(i)}>{t}</button>)}</div><div className="revenue"><span>{view===0?'Facturation du mois':'Solde de trésorerie'}</span><strong>{view===0?'12 480':paid?'10 640':'8 240'}<small>TND</small></strong><svg viewBox="0 0 420 95" role="img" aria-label="Courbe de démonstration de l’activité"><defs><linearGradient id="chart-fill" x1="0" y1="0" x2="0" y2="1"><stop stopColor="#2448ee" stopOpacity=".2"/><stop offset="1" stopColor="#2448ee" stopOpacity="0"/></linearGradient></defs><path d="M0 76C26 76 24 51 55 53S96 85 127 65S162 20 195 29S235 61 270 35S313 57 350 20S396 33 420 5L420 95H0Z" fill="url(#chart-fill)"/><path d="M0 76C26 76 24 51 55 53S96 85 127 65S162 20 195 29S235 61 270 35S313 57 350 20S396 33 420 5" fill="none" stroke="#2448ee" strokeWidth="3"/></svg></div><div className="invoice-row"><span className="invoice-icon"><FileText size={15}/></span><div><strong>FA-2026-0142</strong><span>Client de démonstration</span></div><b>2 400 TND</b></div><button className={`demo-pay ${paid?'done':''}`} onClick={()=>setPaid(p=>!p)}>{paid?<><Check size={16}/> Paiement enregistré</>:<>Simuler un encaissement <ArrowRight size={16}/></>}</button><div className="demo-result" aria-live="polite">{paid?'Votre trésorerie vient d’évoluer. Sans ressaisie.':'Une facture. Un paiement. Une vue d’ensemble.'}</div></div></div>}
function CommerceDemo(){const [qty,setQty]=useState(1),[added,setAdded]=useState(false);return <div className="commerce-demo"><header><b>atelier / 01</b><span>BOUTIQUE DE DÉMONSTRATION</span><ShoppingBag size={18}/></header><div className="shop-item"><div className="shop-art"><div className="vase-neck"/><div className="vase-body"/><span>OBJET N° 001</span><div className="shop-shadow"/></div><div className="shop-details"><span>LA COLLECTION ESSENTIELLE</span><h4>Simple.<br/>Singulier.</h4><p>Un objet fictif.<br/>Une expérience à imaginer.</p><strong>65 <small>€</small></strong><div className="quantity"><button aria-label="Diminuer la quantité" onClick={()=>{setQty(q=>Math.max(1,q-1));setAdded(false)}}><Minus size={14}/></button><span aria-live="polite">{qty}</span><button aria-label="Augmenter la quantité" onClick={()=>{setQty(q=>Math.min(9,q+1));setAdded(false)}}><Plus size={14}/></button></div><button className="shop-add" onClick={()=>setAdded(true)}>{added?<><Check size={16}/> Ajout simulé</>:<>Simuler l’ajout <ArrowUpRight size={16}/></>}</button><span className="shop-total" aria-live="polite">{added?`${qty} article${qty>1?'s':''} · ${qty*65} € dans le panier démo`:'Aucun achat réel'}</span></div></div></div>}
function RestaurantDemo(){const [room,setRoom]=useState(0),[table,setTable]=useState(1);return <div className="restaurant-demo"><header><span>LE RESTAURANT / DÉMO</span><span className="service-tag">SERVICE DU MIDI</span></header><h4>Chaque table.<br/>À sa place.</h4><div className="lab-tabs">{['Salle','Terrasse'].map((t,i)=><button aria-pressed={room===i} key={t} onClick={()=>{setRoom(i);setTable(0)}}>{t}</button>)}</div><div className="floor-plan">{Array.from({length:room===0?6:4},(_,i)=><button key={i} aria-label={`Table ${i+1+room*6}`} aria-pressed={table===i} onClick={()=>setTable(i)}><span className="table-top">{String(i+1+room*6).padStart(2,'0')}</span><i/><i/><i/><i/></button>)}</div><div className="table-summary" aria-live="polite"><span><i/> Table {String(table+1+room*6).padStart(2,'0')} sélectionnée</span><span>{room===0?'Salle intérieure':'Terrasse'}</span></div></div>}
