'use client';

import Image from 'next/image';
import { useState } from 'react';
import { AnimatePresence, motion, useReducedMotion } from 'framer-motion';
import { ArrowRight, ArrowUpRight, Check, Database, FileText, Globe2, Layers3, Network, ShieldCheck, Wifi, Monitor, Camera, RotateCcw } from 'lucide-react';

const ease = [.22, 1, .36, 1] as const;
const mark = <svg viewBox="0 0 32 32" aria-hidden="true"><path d="M7 8h18v6H13v4h12v6H7v-6h12v-4H7Z" fill="currentColor" /></svg>;

export function HeroEcosystem() {
  const [view, setView] = useState(1);
  const reduced = !!useReducedMotion();
  return <div className={`sk-signature view-${view}`}>
    <div className="sk-orbit orbit-one"/><div className="sk-orbit orbit-two"/>
    <motion.div className="sk-infra" style={{zIndex:view===0?4:0}} animate={{ x: view === 0 ? 14 : 0, y: view === 0 ? -12 : 0, rotate: view === 0 ? -3 : -8, opacity: view === 0 ? 1 : .7 }} transition={{duration: reduced ? 0 : .8,ease}}><Image src="/images/infrastructure.jpg" alt="Illustration d’une infrastructure réseau organisée" fill sizes="(max-width: 700px) 60vw, 25vw" priority unoptimized/><div className="sk-infra-shade"/><span><i/>INFRASTRUCTURE</span><div className="sk-infra-ports">{Array.from({length:8},(_,i)=><i key={i}/>)}</div><strong>Des bases solides.</strong></motion.div>
    <svg className="sk-signature-wire" viewBox="0 0 600 500" aria-hidden="true"><path d="M130 190H295V285H440M295 190V85H440"/><circle r="3"><animateMotion dur="5s" repeatCount="indefinite" path="M130 190H295V285H440"/></circle></svg>
    <motion.div className="sk-interface" animate={{x:view === 1 ? 0 : 12,y:view === 2 ? -14 : 0,rotate:view === 1 ? 3 : 0,opacity:view===0?.6:view===2?.8:1}} transition={{duration:reduced?0:.8,ease}}><div className="sk-window"><span><i/><i/><i/></span><span>VOTRE UNIVERS NUMÉRIQUE</span><ArrowUpRight size={12}/></div><div className="sk-interface-brand">{mark}<span>Votre entreprise.</span><span>MENU +</span></div><div className="sk-interface-copy"><span>UNE IDENTITÉ. UNE EXPÉRIENCE.</span><strong>À votre image.<br/><em>À votre mesure.</em></strong><div>Découvrir <ArrowUpRight size={12}/></div></div><div className="sk-interface-art"><div/><div/><div/><span>SC / CONCEPTION SUR MESURE</span></div><footer><span><Globe2 size={12}/> Présence web</span><span>Design & développement</span></footer></motion.div>
    <motion.div className="sk-data-card" style={{zIndex:view===2?5:3}} animate={{y:view===2?-8:0,x:view===2?-9:0,rotate:view===2?-2:-5,scale:view===2?1.07:1}} transition={{duration:reduced?0:.8,ease}}><div><span><Database size={12}/> VOTRE ACTIVITÉ</span><i/></div><strong>Tout se connecte.</strong><svg viewBox="0 0 240 50" aria-hidden="true"><path d="M0 42C20 42 20 20 45 29S70 40 95 19S115 30 143 16S170 36 190 12S222 22 240 4"/></svg><span>Clients · Gestion · Données</span></motion.div>
    <div className="sk-signature-hub">{mark}<span>Un même écosystème.</span></div>
    <nav className="sk-signature-nav" aria-label="Explorer les métiers de SkanCyber">{[{name:'Réseau',icon:Network},{name:'Web',icon:Globe2},{name:'Logiciel',icon:Layers3}].map((v,i)=><button key={v.name} onClick={()=>setView(i)} aria-pressed={view===i} aria-label={`Mettre en lumière ${v.name.toLowerCase()}`}><v.icon size={14}/>{v.name}</button>)}</nav>
  </div>;
}

export function InvoiceStory() {
  const [step, setStep] = useState(0);
  const reduced = !!useReducedMotion();
  return <div className="sk-invoice-story">
    <div className="sk-demo-top"><span>SKANFACT / EN ACTION</span><span>DONNÉES FICTIVES</span></div>
    <div className="sk-invoice-stage"><div className="sk-invoice-modules">{['Client','Facturation','Trésorerie'].map((name,i)=><motion.div key={name} animate={{opacity:step===2?1:.4,y:step===2?0:7}} transition={{duration:reduced?0:.6,delay:reduced?0:i*.12}}><Check size={11}/>{name}</motion.div>)}</div>
      <AnimatePresence mode="wait" initial={false}>{step < 2 ? <motion.div key="invoice" className="sk-draft" initial={{opacity:0,y:20}} animate={{opacity:1,y:0}} exit={{opacity:0,y:-35,scale:.9}} transition={{duration:reduced?0:.45,ease}}><div className="sk-draft-header"><span className="sk-sf">sf.</span><span>{step===0?'BROUILLON':'FACTURE CRÉÉE'}<i className={step===1?'on':''}/></span></div><div className="sk-draft-title"><FileText size={18}/><h4>Une facture.<br/>Tout se met à jour.</h4></div><div className="sk-draft-client"><span>CLIENT DE DÉMONSTRATION</span><strong>Atelier Démo</strong></div><div className="sk-draft-line"><span>{step===0?'Prestation à ajouter':'Prestation de démonstration'}</span><motion.b key={step} initial={reduced?false:{opacity:0,y:5}} animate={{opacity:1,y:0}}>{step===0?'—':'2 400 TND'}</motion.b></div><div className="sk-draft-total"><span>Total</span><motion.strong key={step} initial={reduced?false:{opacity:0,y:5}} animate={{opacity:1,y:0}}>{step===0?'0':'2 400'}<small>TND</small></motion.strong></div><span className="sk-draft-note">{step===0?'Activité initiale : 12 480 TND · Démonstration.':'La facture est prête à rejoindre votre suivi d’activité.'}</span></motion.div> : <motion.div key="dashboard" className="sk-draft sk-demo-dashboard" initial={{opacity:0,y:25,scale:.95}} animate={{opacity:1,y:0,scale:1}} exit={{opacity:0}} transition={{duration:reduced?0:.65,ease}}><div className="sk-draft-header"><span className="sk-sf">sf.</span><span>VUE D’ENSEMBLE<i className="on"/></span></div><span className="sk-dash-label">FACTURATION DU MOIS · DÉMONSTRATION</span><strong className="sk-dash-total">14 880 <small>TND</small></strong><svg viewBox="0 0 320 55" aria-label="Courbe de démonstration" role="img"><motion.path d="M0 48C30 48 30 22 60 34S100 36 125 21S155 37 180 19S230 33 260 12S298 24 320 2" initial={reduced?false:{pathLength:0}} animate={{pathLength:1}} transition={{duration:reduced?0:1.1}}/></svg><div className="sk-new-invoice"><FileText size={13}/><div><strong>Atelier Démo</strong><span>Nouvelle facture intégrée</span></div><b>2 400 TND</b><Check size={13}/></div></motion.div>}</AnimatePresence>
    </div><div className="sk-demo-controls"><span aria-live="polite">{['01 / Composer','02 / Valider','03 / Piloter'][step]}</span><button onClick={()=>setStep(s=>(s+1)%3)}>{['Créer la facture','Intégrer au tableau de bord','Rejouer la démonstration'][step]}{step===2?<RotateCcw size={13}/>:<ArrowRight size={13}/>}</button></div>
  </div>;
}

const access = [{name:'Équipe',icon:Wifi,detail:'Un accès dédié aux outils et aux usages de l’équipe.'},{name:'Caisse',icon:Monitor,detail:'Les équipements de caisse disposent de leur propre réseau.'},{name:'Invités',icon:Globe2,detail:'Les visiteurs utilisent un accès séparé des usages professionnels.'},{name:'Caméras',icon:Camera,detail:'Les caméras sont regroupées sur un réseau distinct.'}];
export function RestaurantStory() {
  const [deployed, setDeployed] = useState(false), [selected, setSelected] = useState(0);
  const reduced = !!useReducedMotion();
  return <div className={`sk-restaurant-story ${deployed?'deployed':''}`}><div className="sk-demo-top"><span>STRASBOURG / EN ACTION</span><span>INSTALLATION UNIFI</span></div><div className="sk-network-stage"><div className="sk-restaurant-hub"><Network size={26}/><strong>Un restaurant.<br/>Quatre usages.</strong><span>UDR 7 · 3 BORNES WI-FI</span><div>{Array.from({length:6},(_,i)=><i key={i}/>)}</div></div><svg className="sk-access-lines" viewBox="0 0 400 110" aria-hidden="true">{[48,150,250,352].map(x=><motion.path key={x} d={`M200 0V32Q200 44 ${x} 44V110`} animate={{pathLength:deployed?1:0,opacity:deployed?1:0}} transition={{duration:reduced?0:.65}}/>)}</svg><div className="sk-access-grid">{access.map((a,i)=><motion.button key={a.name} onClick={()=>{setDeployed(true);setSelected(i)}} aria-label={`Voir les usages du réseau ${a.name.toLowerCase()}`} aria-pressed={deployed&&selected===i} animate={{y:deployed?0:-28,scale:deployed?1:.85,opacity:deployed?1:.45}} transition={{duration:reduced?0:.65,delay:reduced?0:i*.09,ease}}><a.icon size={20}/><strong>{a.name}</strong><span>ACCÈS DISTINCT</span></motion.button>)}</div><div className="sk-network-detail" aria-live="polite"><ShieldCheck size={15}/><p>{deployed?access[selected].detail:'Explorez comment les accès se répartissent selon les usages.'}</p></div></div><div className="sk-demo-controls"><span>{deployed?'04 ACCÈS ORGANISÉS':'01 INFRASTRUCTURE'}</span><button onClick={()=>setDeployed(v=>!v)}>{deployed?'Replier le schéma':'Déployer les accès'}{deployed?<RotateCcw size={13}/>:<ArrowRight size={13}/>}</button></div></div>;
}

export function ContactAssembly() {
  const reduced = !!useReducedMotion();
  return <div className="sk-contact-assembly" aria-hidden="true"><span className="sk-assembly-line"/>{[Network,Globe2,Layers3].map((Icon,i)=><motion.span key={i} className="sk-assembly-part" initial={reduced?false:{x:(i-1)*82,y:-7,opacity:1}} whileInView={{x:0,y:0,opacity:0}} viewport={{once:true,amount:.7}} transition={{duration:reduced?0:1.1,delay:reduced?0:.15+i*.12,ease}}><Icon size={19}/></motion.span>)}<motion.div className="sk-assembly-core" initial={reduced?false:{scale:.6,opacity:0}} whileInView={{scale:1,opacity:1}} viewport={{once:true,amount:.7}} transition={{duration:reduced?0:.8,delay:reduced?0:.85,ease}}>{mark}</motion.div><span className="sk-assembly-caption">UN PARTENAIRE. UNE VISION D’ENSEMBLE.</span></div>;
}
