'use client';
import { useEffect, useRef, useState } from 'react';
import dynamic from 'next/dynamic';
import { AnimatePresence, MotionConfig, motion, useMotionValueEvent, useReducedMotion, useScroll, useSpring, useTransform } from 'framer-motion';
import { ArrowDown, ArrowUpRight, ArrowRight, Check, Menu, X, Wifi, ShieldCheck, Network, Pause, Play, Phone } from 'lucide-react';
import ProductLab, { products } from './ProductLab';
const Sculpture = dynamic(()=>import('./SignalSculpture'),{ssr:false});
const chapters = [
 { verb:'Connecter.', label:'LE SIGNAL CIRCULE', title:'Tout commence\npar une connexion.', copy:'Une caisse. Un terminal. Un ordinateur. Vos outils doivent se parler, partout où votre métier vous emmène.', detail:'Réseau & Wi-Fi professionnels', color:'#2448ee' },
 { verb:'Protéger.', label:'LES ACCÈS SONT MAÎTRISÉS', title:'Laisser passer.\nCe qu’il faut.', copy:'Vos invités se connectent. Votre caisse reste à l’abri. La sécurité crée les bonnes frontières, sans freiner votre activité.', detail:'Cybersécurité & séparation des réseaux', color:'#fc5b35' },
 { verb:'Travailler.', label:'LE SYSTÈME PREND SON SENS', title:'Et votre métier\npeut avancer.', copy:'Facturer. Vendre. Servir. Des logiciels pensés pour vos usages, portés par une infrastructure qui tient la route.', detail:'SkanFact · SkanEcom · SkanRestau', color:'#aabb8e' },
];
function Mark(){return <svg viewBox="0 0 38 38" fill="none" aria-hidden="true"><path d="M9 9h20v8H17v4h12v8H9v-8h12v-4H9Z" fill="currentColor"/><path d="M1 1h36v36H1Z" stroke="currentColor" strokeOpacity=".3"/></svg>}
function Brand(){return <a href="#top" className="brand" aria-label="SkanCyber, accueil"><Mark/><span>skancyber<span className="brand-period">.</span></span></a>}
function SculptureFallback(){return <svg className="sculpture-poster" viewBox="0 0 500 500" fill="none" aria-hidden="true"><defs><linearGradient id="poster-color" x1="0" y1="0" x2="1" y2="1"><stop stopColor="#98b2ff"/><stop offset=".35" stopColor="#2448ee"/><stop offset="1" stopColor="#10246e"/></linearGradient></defs>{Array.from({length:32},(_,i)=><ellipse key={i} cx="250" cy="250" rx={150-i*.65} ry={62+i*1.8} stroke="url(#poster-color)" strokeWidth="4" transform={`rotate(${i*5.625} 250 250)`}/>)}</svg>}
function Scene({phase,paused,reduced,hero=false,choose}:{phase:number;paused:boolean;reduced:boolean;hero?:boolean;choose?:(i:number)=>void}){return <div className={`signal-scene ${hero?'hero-scene':'story-scene'} scene-phase-${phase}`}>
  <div className="scene-grid" aria-hidden="true"/><div className="scene-coordinate top-left">SC / 01<br/>SYSTÈME VIVANT</div><div className="scene-coordinate bottom-right">FR / TN<br/>DEUX TERRAINS. UNE VISION.</div>
  <div className="scene-orbit" aria-hidden="true"/><div className="scene-shadow" aria-hidden="true"/>
  <div className="sculpture-stage"><SculptureFallback/>{!reduced&&<Sculpture phase={phase} paused={paused}/>}</div>
  <span className="scene-status"><i/>{hero?'LE LIEN ENTRE VOS MÉTIERS':chapters[phase].label}</span>
  {hero?<><div className="scene-tag tag-network"><span className="tiny-dot"/>RÉSEAU</div><div className="scene-tag tag-security"><ShieldCheck size={12}/>SÉCURITÉ</div><div className="scene-tag tag-software"><span>↗</span>LOGICIELS</div><div className="scene-hint">Le système réagit à votre mouvement.</div></>:<div className="scene-nodes">{phase<2?['Équipe','Caisse','Invités'].map((n,i)=><div className={`scene-node node-${i}`} key={n}><span>{phase===1&&i===2?<ShieldCheck size={17}/>:<Wifi size={17}/>}</span><b>{n}</b><small>{phase===1&&i===2?'accès isolé':'connecté'}</small></div>):products.map((p,i)=><button key={p.name} className={`scene-node node-${i}`} onClick={()=>choose?.(i)}><span>0{i+1}</span><b>{p.name}</b><small>explorer ↗</small></button>)}</div>}
</div>}
export default function SkanExperience(){
 const [selected,setSelected]=useState(0),[menu,setMenu]=useState(false),[paused,setPaused]=useState(false),[contact,setContact]=useState('Votre projet'),[chapter,setChapter]=useState(0),[zone,setZone]=useState(0),[isolation,setIsolation]=useState(false);
 const reduced=!!useReducedMotion();const still=reduced||paused;const chapterRef=useRef(0);
 const story=useRef<HTMLElement>(null),hero=useRef<HTMLElement>(null);
 const {scrollYProgress}=useScroll();const progress=useSpring(scrollYProgress,{stiffness:100,damping:30});
 const {scrollYProgress:storyProgress}=useScroll({target:story,offset:['start start','end end']});
 const {scrollYProgress:heroProgress}=useScroll({target:hero,offset:['start start','end start']});
 const heroY=useTransform(heroProgress,[0,1],[0,reduced||paused?0:90]);
 useMotionValueEvent(storyProgress,'change',value=>{if(reduced)return;const step=Math.min(2,Math.floor(value*3));if(step!==chapterRef.current){chapterRef.current=step;setChapter(step)}});
 useEffect(()=>{if(!menu)return;const key=(e:KeyboardEvent)=>{if(e.key==='Escape'){setMenu(false);document.getElementById('menu-toggle')?.focus()}};document.addEventListener('keydown',key);return()=>document.removeEventListener('keydown',key)},[menu]);
 useEffect(()=>{if(!menu)return;const first=document.querySelector<HTMLAnchorElement>('.mobile-nav a');first?.focus()},[menu]);
 const select=(i:number)=>{setSelected(i);document.getElementById('solutions')?.scrollIntoView({behavior:reduced?'auto':'smooth'})};
 const ask=(name:string)=>{setContact(name);document.getElementById('contact')?.scrollIntoView({behavior:reduced?'auto':'smooth'})};
 const jump=(i:number)=>{if(reduced){document.getElementById(i===0?'systeme':`etape-${i}`)?.scrollIntoView({behavior:'auto'});return;}if(!story.current)return;const r=story.current.getBoundingClientRect();window.scrollTo({top:scrollY+r.top+(story.current.offsetHeight-innerHeight)*(i/3+.04),behavior:reduced?'auto':'smooth'})};
 const active=chapters[chapter];
 return <MotionConfig reducedMotion="user"><div className="skan-site" id="top" data-paused={paused}>
  <a className="skip-link" href="#content">Aller au contenu</a><motion.div className="reading-progress" style={{scaleX:still?scrollYProgress:progress}}/>
  <header className="site-nav"><Brand/><nav aria-label="Navigation principale"><a href="#systeme">Notre approche</a><a href="#solutions">Les solutions</a><a href="#terrain">Le terrain</a></nav><a className="nav-contact" href="#contact">Parlons de votre projet <ArrowUpRight size={16}/></a><button id="menu-toggle" className="menu-toggle" aria-label={menu?'Fermer le menu':'Ouvrir le menu'} aria-expanded={menu} aria-controls="mobile-navigation" onClick={()=>setMenu(m=>!m)}>{menu?<X/>:<Menu/>}</button><AnimatePresence>{menu&&<motion.nav id="mobile-navigation" className="mobile-nav" aria-label="Navigation mobile" initial={{opacity:0,y:still?0:-8}} animate={{opacity:1,y:0}} exit={{opacity:0}}>{[['Notre approche','systeme'],['Les solutions','solutions'],['Le terrain','terrain'],['Votre projet','contact']].map(([t,id],i)=><a key={id} href={`#${id}`} onClick={()=>setMenu(false)}><span>0{i+1}</span>{t}<ArrowUpRight/></a>)}</motion.nav>}</AnimatePresence></header>
  <main id="content">
   <section className="hero-section" ref={hero}>
    <div className="hero-topline"><span className="eyebrow"><i/>LE GROUPE SKANCYBER</span><span className="hero-edition">RÉSEAU / SÉCURITÉ / LOGICIELS</span></div>
    <div className="hero-layout"><div className="hero-copy"><h1><span>Votre métier.</span><span>Sans <span className="friction-word">friction<svg viewBox="0 0 600 24" preserveAspectRatio="none" aria-hidden="true"><motion.path d="M4 15Q265 0 593 10" fill="none" stroke="currentColor" strokeWidth="5" initial={false} animate={{pathLength:1}}/></svg></span><span className="hero-stop">.</span></span></h1><div className="hero-description"><span className="hero-cross" aria-hidden="true">✳</span><p>Le réseau qui vous connecte.<br/>La sécurité qui vous protège.<br/><strong>Les logiciels qui vous font avancer.</strong></p></div><a className="solid-action" href="#systeme">Entrez dans le système <ArrowDown size={18}/></a></div><motion.div className="hero-art" style={{y:heroY}}><Scene hero phase={selected} paused={paused} reduced={reduced}/></motion.div></div>
    <div className="hero-bottom"><span>UNE VUE D’ENSEMBLE.<br/>UN SEUL INTERLOCUTEUR.</span><a className="scroll-cue" href="#systeme"><ArrowDown size={15}/> DÉFILER POUR CONNECTER LES POINTS</a><button className="motion-control" onClick={()=>setPaused(p=>!p)} aria-label={paused?'Activer les animations':'Mettre les animations en pause'}>{paused?<Play size={12}/>:<Pause size={12}/>}<span>{paused?'MOTION EN PAUSE':'MOTION ACTIVÉ'}</span></button></div>
   </section>
   <div className="solutions-band"><span className="band-label">LA FAMILLE<br/>SKANCYBER ↘</span>{products.map((p,i)=><button key={p.name} onClick={()=>select(i)}><span>0{i+1}</span>{p.name}<ArrowUpRight/></button>)}</div>
   <section className={`story-section ${reduced?'reduced-story':''}`} id="systeme" ref={story}>
    <div className="story-sticky"><div className="section-index"><span>01 — RELIER LES POINTS</span><span>LE MÊME SYSTÈME, DU DÉBUT À LA FIN.</span></div><div className="story-layout"><div className="story-narrative"><div className="chapter-controls" aria-label="Les étapes du système">{chapters.map((c,i)=><button aria-pressed={chapter===i} onClick={()=>jump(i)} key={c.verb}><span>0{i+1}</span>{c.verb}</button>)}</div><AnimatePresence mode="wait" initial={false}><motion.div className="chapter-copy" key={chapter} initial={{opacity:still?1:0,y:still?0:20}} animate={{opacity:1,y:0}} exit={{opacity:still?1:0,y:still?0:-15}} transition={{duration:still?0:.25}}><span className="chapter-number">/ 0{chapter+1}</span><h2>{active.title}</h2><p>{active.copy}</p><span className="chapter-service"><i style={{background:active.color}}/>{active.detail}</span></motion.div></AnimatePresence><div className="story-track"><span>UNE VISION D’ENSEMBLE</span><div>{chapters.map((c,i)=><i key={c.verb} className={chapter>=i?'filled':''}/>)}</div><span>0{chapter+1} / 03</span></div></div><Scene phase={chapter} paused={paused} reduced={reduced} choose={select}/></div><div className="story-footer"><span>DES CONNEXIONS UTILES. DES FRONTIÈRES CLAIRES. DES OUTILS ADAPTÉS.</span><a href="#solutions">C’est là que tout prend forme <ArrowDown size={15}/></a></div></div>
    {reduced&&<div className="reduced-chapters">{chapters.slice(1).map((c,i)=><article key={c.verb} id={`etape-${i+1}`}><h3>{c.verb}</h3><p>{c.copy}</p></article>)}</div>}
   </section>
   <ProductLab selected={selected} onSelect={setSelected} ask={ask} reduced={still}/>
   <section className="terrain-section" id="terrain"><div className="section-index"><span>03 — CE QUI SE PASSE VRAIMENT</span><span>STRASBOURG, FRANCE</span></div><div className="terrain-intro"><div><span className="eyebrow"><i/>UNE RÉALISATION DE TERRAIN</span><h2>Le service continue.<br/><span>Le réseau suit.</span></h2></div><p>Dans un restaurant, l’informatique se juge en plein service. Un terminal passe de la salle à la terrasse. Le Wi-Fi des clients reste séparé de la caisse.</p></div><div className="terrain-experience"><div className="restaurant-map"><div className="map-caption"><span>PLAN D’INSTALLATION / SCHÉMA</span><span>PROJET RÉEL ↗</span></div><div className="map-drawing"><svg viewBox="0 0 640 320" aria-hidden="true"><path className="room-outline" d="M34 35H380V100H610V284H34ZM380 100V284M34 180H380M200 35V180"/><path className="network-cable" d="M310 234V130H114V89M310 130H515V191M310 130V78"/><path className="signal-packet" d="M310 234V130H114V89M310 130H515V191M310 130V78"/></svg><div className="map-router"><Network size={17}/><span>UDR 7</span></div>{['Salle','Terrasse','Cuisine'].map((n,i)=><button key={n} aria-pressed={zone===i} className={`access-point point-${i}`} onClick={()=>setZone(i)}><span className="ap-circle"><Wifi size={21}/>{zone===i&&<motion.span className="ap-signal" layoutId="access-signal" transition={{duration:still?0:.5}}/>}</span><strong>{n}</strong><small>{zone===i?'terminal connecté':'borne Wi-Fi'}</small></button>)}<span className="map-table table-a"/><span className="map-table table-b"/><span className="map-table table-c"/><span className="map-table table-d"/></div><div className="roaming-status"><span className="eyebrow"><i/>TERMINAL DE PAIEMENT</span><span aria-live="polite">{['Salle','Terrasse','Cuisine'][zone]} <ArrowRight size={13}/> connexion maintenue</span></div></div><div className="terrain-data"><span className="eyebrow">L’INSTALLATION</span><div className="installation-stats"><div><strong>03</strong><span>BORNES WI-FI</span></div><div><strong>04</strong><span>RÉSEAUX ISOLÉS</span></div><div><strong>24</strong><span>PORTS SUR LE SWITCH</span></div></div><p>Un routeur UniFi Dream Router 7, un switch 24 ports et trois bornes. Une installation pensée pour les usages du restaurant.</p><div className={`isolation-control ${isolation?'isolated':''}`}><div><ShieldCheck size={19}/><span aria-live="polite">{isolation?'Invités → caisse : accès bloqué.':'Un invité peut-il accéder à la caisse ?'}</span></div><button onClick={()=>setIsolation(v=>!v)}>{isolation?'Réinitialiser':'Tester l’isolation'}{isolation?<Check size={15}/>:<ArrowRight size={15}/>}</button></div><small>Interaction simulée. Matériel et séparation des réseaux issus du projet réel.</small></div></div></section>
   <section className="founder-section"><div className="founder-monogram" aria-hidden="true">SB<span>LE FIL<br/>CONDUCTEUR.</span><svg viewBox="0 0 460 80"><path d="M0 40H155Q190 0 220 40T285 40H460" fill="none" stroke="currentColor" strokeWidth="2"/></svg></div><div className="founder-copy"><span className="eyebrow">04 — DERRIÈRE LE SYSTÈME</span><h2>La même personne.<br/>Une vue <span>d’ensemble.</span></h2><p>Je suis Skander Ben Amor, fondateur de SkanCyber. Développeur d’applications métier, formé à la cybersécurité. Je peux parler de votre réseau et du logiciel qui s’y connecte.</p><p className="founder-line">Vous parlez de votre activité.<br/>On pense l’informatique autour.</p><span className="founder-signature">Skander Ben Amor <ArrowUpRight size={16}/><small>FONDATEUR & GÉRANT</small></span></div></section>
   <section className="contact-section" id="contact"><div className="section-index"><span>05 — LA SUITE S’ÉCRIT AVEC VOUS</span><span>À DISTANCE, AU PLUS PRÈS DE VOTRE MÉTIER.</span></div><div className="contact-layout"><div><h2>On connecte<br/><span>les points ?</span><ArrowUpRight className="contact-arrow"/></h2><p>Un projet, une question, un outil qui vous ralentit.<br/>Commençons par votre quotidien.</p><div className="contact-topic"><label htmlFor="project-topic">VOTRE SUJET</label><select id="project-topic" value={contact} onChange={e=>setContact(e.target.value)}>{['Votre projet',...products.map(p=>p.name),'Réseau & sécurité','Logiciel sur mesure'].map(n=><option key={n}>{n}</option>)}</select></div></div><div className="contact-links"><span className="eyebrow">PARLONS-EN DIRECTEMENT</span><a href="tel:+33672313188"><span>FRANCE</span><strong>+33 6 72 31 31 88</strong><ArrowUpRight/></a><a href="tel:+21650800600"><span>TUNISIE</span><strong>+216 50 800 600</strong><ArrowUpRight/></a><span className="contact-note"><Phone size={13}/> Un échange pour comprendre. Un devis pour avancer.</span></div></div><div className="contact-bigword" aria-hidden="true">À vous de jouer<span>↗</span></div></section>
  </main>
  <footer className="site-footer"><div className="footer-top"><Brand/><span>UN GROUPE.<br/>UNE VUE D’ENSEMBLE.</span><a href="#top">RETOUR EN HAUT <ArrowUpRight size={16}/></a></div><details className="legal"><summary>Informations légales & précisions</summary><div><p>SKANCYBER SECURITY SUARL — gestion d’installations informatiques. 08 Rue de l’Université, Manar 1, El Menzah, Tunis 2092, Tunisie. Matricule fiscal : 1998268 D/A/M/000. Gérant : Skander Ben Amor.</p><p>« Groupe » désigne la famille de solutions SkanCyber, sans affirmer une structure juridique supplémentaire. Les interfaces interactives sont des démonstrations avec des données fictives. SkanEcom et SkanRestau présentent des concepts d’interface ; leur périmètre et leur disponibilité sont à préciser lors d’un échange. Aucune interconnexion entre les produits n’est promise.</p><p>Hébergement : Vercel Inc. Polices hébergées localement. Aucun cookie de suivi ni mesure d’audience. Les zones d’intervention sur place et les modalités de chaque prestation sont définies avec vous.</p></div></details><div className="footer-bottom"><span>© {2026} SKANCYBER SECURITY SUARL</span><span>DU TERRAIN AUX BONS OUTILS.</span><a href="#contact">FR / TN</a></div></footer>
 </div></MotionConfig>;
}
