'use client';
import {useEffect,useRef,useState} from 'react';
import {motion,useReducedMotion,useScroll,useTransform} from 'framer-motion';
import {Check,ShieldCheck,ArrowUpRight,Wifi,Mail,RefreshCw,Monitor,Smartphone,Globe,CloudOff,FileCheck2,CalendarClock,Phone,Activity,Database,Network,Pause,Play} from 'lucide-react';
import {DemoTag} from './Demos';

function useDemo(period=2400){
 const ref=useRef<HTMLDivElement>(null),[tick,setTick]=useState(0),[paused,setPaused]=useState(false),[visible,setVisible]=useState(false);const reduced=useReducedMotion();
 useEffect(()=>{const el=ref.current;if(!el)return;const o=new IntersectionObserver(([e])=>setVisible(e.isIntersecting),{threshold:.15});o.observe(el);return()=>o.disconnect()},[]);
 useEffect(()=>{if(paused||reduced||!visible)return;const t=setInterval(()=>{if(!document.hidden)setTick(x=>x+1)},period);return()=>clearInterval(t)},[period,paused,reduced,visible]);
 return {ref,tick,paused,setPaused,setTick};
}
function Playback({paused,toggle}:{paused:boolean;toggle:()=>void}){return <button className="demo-control" aria-label={paused?'Reprendre la démonstration':'Mettre la démonstration en pause'} onClick={toggle}>{paused?<Play size={13}/>:<Pause size={13}/>}</button>}
function PanelHead({title,demo}:{title:string;demo:ReturnType<typeof useDemo>}){return <div className="panel-label"><span>{title}</span><DemoTag/><Playback paused={demo.paused} toggle={()=>demo.setPaused(!demo.paused)}/></div>}
export function NightDemo(){const d=useDemo(2100),phase=d.tick%6;const events=[['00:42','sauvegarde terminée',false],['01:17','connexion suspecte bloquée',true],['02:08','mise à jour appliquée',false],['03:26','tentative d’accès bloquée',true],['05:10','sauvegarde vérifiée',false],['07:00','rapport du matin prêt',false]] as const;return <div ref={d.ref} className="visual-panel night-demo"><PanelHead title="journal de la nuit / 24 h" demo={d}/><div className="night-display"><div className="clock-ring"><svg viewBox="0 0 240 240" aria-hidden="true"><circle cx="120" cy="120" r="97" className="ring-base"/>{Array.from({length:48},(_,i)=>{const a=i*Math.PI/24;return <line key={i} x1={Number((120+Math.sin(a)*101).toFixed(3))} y1={Number((120-Math.cos(a)*101).toFixed(3))} x2={Number((120+Math.sin(a)*(i%2?106:111)).toFixed(3))} y2={Number((120-Math.cos(a)*(i%2?106:111)).toFixed(3))} stroke="#7da799" strokeOpacity={i%2?.3:.65}/>})}{events.map((e,i)=>{const a=(i*3+2)*Math.PI/12;return <circle key={i} cx={Number((120+Math.sin(a)*97).toFixed(3))} cy={Number((120-Math.cos(a)*97).toFixed(3))} r={i===phase?5:3} fill={e[2]?'#FF5D4F':'#34F5C5'} opacity={i<=phase?1:.22}/>})}<circle cx="120" cy="120" r="78" className="ring-inner"/></svg><div><ShieldCheck size={25}/><strong>07:00</strong><span>vous pouvez ouvrir.</span></div></div><div className="night-stats"><div><strong>{12+phase*3}</strong><span>tentatives bloquées</span></div><div><strong>{1+Math.floor(phase/3)}</strong><span>sauvegardes</span></div><div><strong>{phase>1?'01':'00'}</strong><span>mise à jour</span></div></div></div><div className="night-log" aria-label="Événements simulés">{events.slice(Math.max(0,phase-2),phase+1).map(([time,text,blocked])=><div key={time} className={blocked?'blocked':''}><time>{time}</time><span>{text}</span>{blocked?<ShieldCheck size={13}/>:<Check size={13}/>}</div>)}</div></div>}
export function AuditDemo(){const d=useDemo(1300),count=d.tick%7,items=['Mots de passe par défaut','Mises à jour des équipements','Ports ouverts sur internet','Wi-Fi invités isolé','Sauvegardes'];return <div ref={d.ref} className="visual-panel audit-demo"><PanelHead title="audit / points de contrôle" demo={d}/><div className="audit-summary"><div><span className="micro">lecture de votre installation</span><h3>Une priorité claire.<br/>À chaque point.</h3></div><div className="score-ring"><svg viewBox="0 0 100 100" aria-hidden="true"><circle className="ring-base" cx="50" cy="50" r="42"/><circle className="score-progress" cx="50" cy="50" r="42" strokeDasharray="264" strokeDashoffset={264-Math.min(count,5)*.2*211}/></svg><strong>{Math.min(count,5)*16}<small>/100</small></strong></div></div><div className="audit-checks">{items.map((x,i)=><div key={x}><span className={'audit-indicator '+(i<count?(i===0?'risk':'ok'):'')}>{i<count?(i===0?'!':<Check size={12}/>):String(i+1).padStart(2,'0')}</span><span>{x}</span><small className={i===0&&i<count?'blocked':''}>{i<count?(i===0?'accès exposé':'vérifié'):'à vérifier'}</small></div>)}</div><div className="audit-report"><FileCheck2 size={17}/><span>rapport priorisé · explications simples</span><button onClick={()=>{d.setTick(0);d.setPaused(false)}} aria-label="Relancer la démonstration d’audit"><RefreshCw size={14}/></button></div><p className="micro demo-footnote">score fictif · ne constitue pas un audit réel</p></div>}

export function WebsiteDemo(){const d=useDemo(2300),step=d.tick%4;return <div ref={d.ref} className="visual-panel website-demo"><PanelHead title="votre site / premier point de contact" demo={d}/><div className="web-stage"><div className="mini-browser"><div className="mini-address"><span>● ● ●</span><span>votre-commerce.exemple</span></div><div className="mini-site"><span className="mini-logo">atelier / démo</span><span className="micro">un espace à votre image</span><h3>Votre prochain<br/>projet commence <em>ici.</em></h3><div className="mini-cta">Parlons de votre projet</div><div className="mini-site-lines"><span/><span/><span/></div></div></div><div className="site-signals"><div><Activity size={16}/><strong>{128+d.tick%30}</strong><span>visites · démo</span></div><div><Mail size={16}/><strong>{3+step}</strong><span>demandes reçues</span></div><div><Globe size={16}/><strong>{[384,362,371,358][step]}<small> ms</small></strong><span>chargement simulé</span></div></div></div><motion.div className="incoming-contact" key={step} initial={{opacity:.4,y:6}} animate={{opacity:1,y:0}}><span className="signal-dot"/><span>nouvelle demande de devis</span><b>transmise au crm</b><Check size={14}/></motion.div></div>}
export function CRMDemo(){const d=useDemo(2400),step=d.tick%4;return <div ref={d.ref} className="visual-panel crm-story"><PanelHead title="crm / chaque contact a une suite" demo={d}/><div className="crm-topline"><span className="micro"><span className="signal-dot"/> demande reçue du site</span><span className="micro">contact fictif</span></div><div className="story-pipeline">{['Nouveau','Contacté','Devis','Signé'].map((x,i)=><div key={x}><header><i/>{x}<small>{i===step?'01':'00'}</small></header>{i===step&&<motion.article layoutId="story-lead" transition={{type:'tween',duration:.65}}><span className="micro">prospect #0042</span><h4>Projet d’aménagement</h4><span>Contact de démonstration</span><strong>2 400 €</strong><small>{['à rappeler','besoin qualifié','devis envoyé','accord reçu'][step]}</small></motion.article>}</div>)}</div><div className="crm-detail"><div><CalendarClock size={18}/><span>prochaine étape<b>{step===3?'Préparer le lancement':'Relance planifiée · demain, 10 h'}</b></span></div><div className="crm-history"><span><i/> formulaire reçu</span><span><i/> échange enregistré</span><span><i/> responsable attribué</span></div></div></div>}

export function CustomDemo(){const d=useDemo(2700),step=d.tick%3;return <div ref={d.ref} className="custom-demo"><div className="custom-demo-toolbar"><span className="micro">une logique métier / trois formats</span><DemoTag/><Playback paused={d.paused} toggle={()=>d.setPaused(!d.paused)}/></div><div className="device-row"><div className="device web-device"><div className="device-chrome"><Globe size={14}/><span>web</span><span>● ● ●</span></div><div className="device-content"><small>espace de travail</small><h3>Bonjour, l’équipe.</h3><div className="mini-metrics"><span><b>{24+step}</b>dossiers</span><span><b>{6-step}</b>à suivre</span></div>{['Commande reçue','Dossier attribué','Client informé'].map((x,i)=><div className={'device-task '+(i===step?'current':'')} key={x}><Check size={11}/>{x}</div>)}</div></div><div className="device desktop-device"><div className="device-chrome"><Monitor size={14}/><span>bureau</span><span>— □ ×</span></div><div className="device-content"><small>gestion quotidienne</small><h3>Ça marche. Même ici.</h3><div className="offline-status"><CloudOff size={18}/><span>sans connexion internet</span></div><div className="local-save"><Check size={15}/>{step+1} modification{step?'s':''} enregistrée{step?'s':''} localement</div><span className="micro">electron / fonctions selon projet</span></div></div><div className="phone-device"><div className="phone-notch"/><div className="phone-time">09:41 <Wifi size={10}/></div><div className="device-content"><small>mobile</small><h3>Sur le terrain.</h3><div className="phone-task"><span className="micro">intervention #042</span><strong>{['À préparer','En cours','Terminée'][step]}</strong><div className="phone-progress"><span style={{width:(step+1)*33.33+'%'}}/></div><span>Tout est à jour.</span></div><div className="phone-tabs"><Globe size={14}/><CalendarClock size={14}/><Check size={14}/></div></div></div></div><div className="tech-chips">{['Next.js','React','TypeScript','Supabase','Electron','PWA / Expo','Vercel'].map(t=><span key={t}>{t.toLowerCase()}</span>)}</div></div>}
export function ConnectedDemo(){const d=useDemo(2100),step=d.tick%3;return <div ref={d.ref} className="connected-demo visual-panel"><PanelHead title="votre entreprise / pensée ensemble" demo={d}/><div className="connected-apps">{[[Globe,'site','le contact arrive'],[Mail,'crm','la relation avance'],[Database,'erp','la gestion suit']].map(([Icon,name,text],i)=>{const I=Icon as typeof Globe;return <div className={i===step?'connected-active':''} key={String(name)}><I size={25}/><b>{String(name)}</b><span>{String(text)}</span></div>})}</div><div className="secure-foundation"><ShieldCheck size={21}/><span>réseau sécurisé</span><span className="micro">la base commune</span></div><div className="one-contact"><Phone size={15}/><span>un seul interlocuteur</span><span className="micro">du réseau au logiciel</span></div></div>}
export function MethodProgress(){const ref=useRef<HTMLDivElement>(null),reduced=useReducedMotion();const {scrollYProgress}=useScroll({target:ref,offset:['start 80%','end 50%']});return <div ref={ref} className="method-v2"><div className="method-track"><motion.span style={{scaleX:reduced?1:scrollYProgress}}/></div>{[['01','Écoute & audit','Comprendre votre quotidien et examiner les outils déjà en place.','vos usages, avant tout'],['02','Plan & devis','Définir le périmètre, les connexions et un budget lisible.','une proposition claire'],['03','Construction & installation','Avancer avec des démonstrations régulières, puis vérifier les parcours.','vous voyez ce qui avance'],['04','Suivi','Cadrer la maintenance et faire évoluer ce qui doit l’être.','modalités [À CONFIRMER]']].map(([n,t,p,label])=><div key={n}><span className="method-dot"/><span className="micro">{n}</span><h3>{t}</h3><p>{p}</p><span className="micro method-label">{label}</span></div>)}</div>}
export function PageMotion(){const reduced=useReducedMotion();useEffect(()=>{if(reduced)return;const items=document.querySelectorAll('.reveal');const observer=new IntersectionObserver(es=>{es.forEach(e=>{if(e.isIntersecting){e.target.classList.add('revealed');observer.unobserve(e.target)}})},{threshold:.08});items.forEach(el=>{el.classList.add('will-reveal');observer.observe(el)});return()=>{observer.disconnect();items.forEach(el=>el.classList.remove('will-reveal'))}},[reduced]);useEffect(()=>{const cursor=document.querySelector<HTMLElement>('.cursor-ring');if(!cursor||reduced)return;let x=0,y=0,raf=0;const update=(e:PointerEvent)=>{x=e.clientX;y=e.clientY;if(!raf)raf=requestAnimationFrame(()=>{cursor.style.transform=`translate3d(${x-15}px,${y-15}px,0)`;cursor.style.opacity='1';raf=0})};const hide=()=>{cursor.style.opacity='0'};document.addEventListener('pointermove',update);document.addEventListener('pointerleave',hide);return()=>{cancelAnimationFrame(raf);document.removeEventListener('pointermove',update);document.removeEventListener('pointerleave',hide)}},[reduced]);return <div className="cursor-ring" aria-hidden="true"/>}
